Repository vmware/terraform-provider-vcf, pull requests merged in 2023-09, with the labels that each got.

#53 feat: add domain resource import
  CHANGELOG.md
  README.md
  docs/data-sources/domain.md
  docs/index.md
  docs/resources/domain.md
  examples/resources/domain/vcf_domain.tf
  internal/cluster/cluster_operations.go
  internal/domain/domain_operations.go
  internal/network/nsx_manager_subresource.go
  internal/network/nsx_subresource.go
  internal/provider/data_source_domain.go
  internal/provider/data_source_domain_test.go
  internal/provider/resource_domain.go
  internal/provider/resource_domain_test.go
  internal/vcenter/vcenter_subresource.go
Labels: documentation, breaking-change, feature, needs-review

#59 Add validation to NSX-T form_factor parameter.
  docs/resources/domain.md
  internal/network/nsx_subresource.go
Labels: documentation, needs-review

#60 feat: add support for ip pool range creation during cluster/domain creation
  CHANGELOG.md
  docs/resources/cluster.md
  docs/resources/domain.md
  internal/cluster/cluster_operations.go
  internal/network/ip_address_pool_subresource.go
  internal/network/nsx_subresource.go
  internal/provider/resource_cluster.go
  internal/provider/resource_cluster_test.go
  internal/validation/validation_utils.go
  internal/validation/validation_utils_test.go
Labels: documentation, enhancement, needs-review
