Repository vmware/terraform-provider-vcf, pull requests merged in 2023-08, with the labels that each got.

#40 feat: extend support for workload domain cluster expansion and contraction
  docs/index.md
  docs/resources/cluster.md
  examples/resources/cluster/variables.tf
  examples/resources/cluster/vcf_cluster.tf
  internal/cluster/cluster_operations.go
  internal/constants/constants.go
  internal/provider/provider_test.go
  internal/provider/resource_cluster.go
  internal/provider/resource_cluster_test.go
  internal/provider/resource_domain.go
  internal/provider/resource_domain_test.go
  internal/provider/sddc_manager_client.go
  internal/resource_utils/resource_utils.go
Labels: enhancement, needs-review

#43 feat: add cluster datasource and cluster resource import
  docs/data-sources/cluster.md
  docs/data-sources/domain.md
  docs/resources/cluster.md
  docs/resources/domain.md
  examples/data-sources/cluster/variables.tf
  examples/data-sources/cluster/vcf_cluster.tf
  internal/cluster/cluster_operations.go
  internal/cluster/host_spec_subresource.go
  internal/constants/constants.go
  internal/network/nioc_bandwidth_allocation_subresource.go
  internal/network/portgroup_subresource.go
  internal/network/vds_subresource.go
  internal/network/vmnic_subresource.go
  internal/provider/data_source_cluster.go
  internal/provider/data_source_cluster_test.go
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/resource_cluster.go
Labels: documentation, feature, needs-review, resource, datasource

#46 validation_utils IsEmpty doesn't check for boolean values
  internal/validation/validation_utils.go
Labels: needs-review

#47 Fix domain update and expand E2E
  internal/provider/resource_cluster.go
  internal/provider/resource_domain.go
  internal/provider/resource_domain_test.go
Labels: bug, needs-review

#48 Update documentation for v0.3.0 release
  CHANGELOG.md
  docs/resources/cluster.md
Labels: documentation, needs-review

#50 Implement Host import, fix Cluster import
  CHANGELOG.md
  docs/data-sources/cluster.md
  docs/resources/host.md
  examples/resources/cluster/vcf_cluster.tf
  examples/resources/domain/vcf_domain.tf
  internal/cluster/cluster_operations.go
  internal/provider/data_source_cluster.go
  internal/provider/data_source_cluster_test.go
  internal/provider/resource_cluster.go
  internal/provider/resource_cluster_test.go
  internal/provider/resource_host.go
  internal/provider/resource_host_test.go
Labels: documentation, breaking-change, feature, needs-review, refactor
