Repository vmware/terraform-provider-vcf, pull requests merged in 2024-11, with the labels that each got.

#263 feat: simplify response handling
  go.mod
  go.sum
  internal/api_client/sddc_manager_client.go
  internal/api_client/sddc_manager_client_test.go
  internal/api_client/task_tracker.go
  internal/certificates/certificate_operations.go
  internal/cluster/cluster_operations.go
  internal/credentials/credential_operations.go
  internal/domain/domain_operations.go
  internal/network/nsx_subresource.go
  internal/nsx_edge_cluster/edge_cluster_operations.go
  internal/provider/data_network_pool.go
  internal/provider/data_source_domain.go
  internal/provider/resource_ceip.go
  internal/provider/resource_certificate.go
  internal/provider/resource_certificate_authority.go
  internal/provider/resource_cluster.go
  internal/provider/resource_cluster_personality.go
  internal/provider/resource_csr.go
  internal/provider/resource_domain.go
  internal/provider/resource_edge_cluster.go
  internal/provider/resource_external_certificate.go
  internal/provider/resource_host.go
  internal/provider/resource_network_pool.go
  internal/provider/resource_user.go
  internal/provider/resource_vcf_instance.go
Labels: enhancement, dependencies, chore, needs-review, technical-debt, provider

#247 chore: update golangci-lint
  .golangci.yml
Labels: chore, needs-review

#257 chore: update codeowners
  CODEOWNERS
Labels: chore, needs-review

#236 feat: add `d/host`
  docs/data-sources/host.md
  examples/data-sources/host/variables.tf
  examples/data-sources/host/vcf_host.tf
  internal/provider/data_host.go
  internal/provider/data_host_test.go
  internal/provider/provider.go
Labels: documentation, enhancement, needs-review, datasource, provider

#267 chore(release) v0.12.0
  CHANGELOG.md
  README.md
Labels: documentation, needs-review

#270 chore(deps): bump SDK for vcf 5.2.1
  README.md
  docs/index.md
  docs/resources/edge_cluster.md
  go.mod
  go.sum
  internal/nsx_edge_cluster/edge_cluster_operations.go
  internal/nsx_edge_cluster/edge_node_subresource.go
  internal/provider/resource_ceip.go
  internal/provider/resource_edge_cluster.go
  internal/provider/resource_edge_cluster_test.go
Labels: documentation, dependencies, chore, needs-review, provider

#272 chore(release) v0.13.0
  CHANGELOG.md
Labels: documentation, needs-review
