Repository vmware/terraform-provider-vcf, pull requests merged in 2024-04, with the labels that each got.

#148 Fix cluster creation with a vLCM image
  internal/cluster/cluster_operations.go
Labels: needs-review, provider

#150 Remove BGP peer password requirement
  docs/resources/edge_cluster.md
  internal/nsx_edge_cluster/edge_node_subresource.go
Labels: documentation, dco-required, needs-review, provider

#153 chore: add supported versions to docs
  README.md
  docs/index.md
Labels: documentation, needs-review

#154 feat: Support for vSAN Stretched Clusters
  docs/resources/cluster.md
  internal/cluster/cluster_operations.go
  internal/constants/constants.go
  internal/provider/resource_cluster.go
  internal/provider/resource_cluster_test.go
  internal/vsan/witness_host_subresource.go
Labels: documentation, needs-review, provider

#160 chore: Prepare changelog for v0.8.5
  CHANGELOG.md
Labels: documentation, needs-review
