Repository vmware/terraform-provider-vcf, pull requests merged in 2025-08, with the labels that each got.

#346 chore: update version compatibility
  README.md
  docs/index.md
Labels: documentation, needs-review

#350 docs: update component sizing
  docs/resources/domain.md
  docs/resources/instance.md
Labels: documentation, needs-review

#355 chore: update instance example for v9
  examples/resources/instance/main.tf
  examples/resources/instance/terraform.tfvars
  examples/resources/instance/variables.tf
  examples/resources/instance/vcf_instance.tf
  examples/resources/instance/versions.tf
Labels: documentation, needs-review

#352 fix: update values for `appliance_size`
  docs/resources/instance.md
  internal/provider/resource_vcf_instance_test.go
  internal/sddc/sddc_vcf_operations_collector_subresource.go
Labels: bug, documentation, needs-review, provider

#358 refactor: slice initializations to var syntax
  internal/cluster/cluster_operations.go
  internal/cluster/host_spec_subresource.go
  internal/datastores/vmfs_datastore_subresource.go
  internal/datastores/vsan_remote_datastore_cluster_subresource.go
  internal/network/ip_address_pool_subresource.go
  internal/network/vds_subresource.go
  internal/provider/data_host.go
Labels: needs-review, refactor, provider

#359 chore: remove unused constants
  internal/constants/constants.go
  internal/credentials/constants.go
Labels: chore, needs-review, provider
